### ISSUE TITLE
Rename gem to screen-recorder

### ISSUE THREAD

**Issue by kapoorlakshya** [kapoorlakshya/screen-recorder#45]
Once #32 is merged, we will no longer be using and exposing the `FFMPEG` namespace. The `ffmpeg` in the name can hence be dropped and the name can be simplified to `screen-recorder` to match the new namespace `ScreenRecorder`.

**TODO**

- [x] Create screen-recorder repo
- [x] Add a post-install message to `beta13`
- [x] Release `beta13`
- [x] Rename Github repository
- [x] Create ffmpeg-screenrecorder (for Google) and add link to new repo in README
- [x] Update references in Travis and Code Climate.
- [x] Merge #43
- [x] Update `README` and `CHANGES` files
- [ ] Release `screen_recorder 1.0.0`
- [x] Update blog post
- [ ] Update example Cucumber project

**Resources**

https://brandonhilkert.com/blog/ruby-gem-post-install-message/

**Comment by kapoorlakshya** [comment]
Well... I just learned that `screen_recorder` is already taken 😑. The current name will stay, and I will be releasing `beta12` with the post install message removed.

**Comment by kapoorlakshya** [comment]
Decided to use `screen-recorder`.
